# Generated by Django 5.2.6 on 2025-09-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Footbal Shoes'), ('ball', 'Ball'), ('photocard', 'Photocard'), ('accessories', 'Accessories')], default='update', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0)),
                ('visitor', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
