# Generated by Django 5.2.6 on 2025-09-16 12:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Footbal Shoes'), ('ball', 'Ball'), ('photocard', 'Photocard'), ('accessories', 'Accessories')], default='jersey', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('viewers', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
